server:
 port: 8901
 
 
spring:
  application:
    name: apartment-gateway
  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
            - GET
            - POST
            - OPTIONS
  
 
management:
  endpoints:
    web:
      exposure:
        include: "*"          
  endpoint:
    health:
      enabled: true


jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
          
        

