spring:
  application:
    name: user-service
server:
  port: 8081
  eureka: 
    client: 
     serviceUrl: 
       defaultZone:  http://localhost:9001/eureka/


  h2: 
    console:  
      enabled:  true
  jpa:
    show-sql: false
    

